<h1 style="color:white;background:rgba(255,50,50,0.8);padding:10px;border-radius:10px;text-align:center;"> Vectors and Vector Arithmetic using numpy -<sub>By Ali Abbas</sub></h1>

In [5]:
import numpy as np
from numpy import array
from math import inf
from math import sqrt
#Defining a vector
v1= array([1,2,3])
v2= array([1,2,3])
#vector addition
a=v1+v2
print(a)

#vector Substraction
a=v1-v2
print(a)

#vector Multiplication
a=v1*v2
print(a)

#vector Division
a=v1/v2
print(a)

#Calculating the dot product between vectors v1 and v2
#v1[0]*v2[0]+v1[1]*v2[1]....v1[n]*v2[n]
a=v1.dot(v2)
a


[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


14

<h2 style="color:white;background:rgba(255,90,90,0.8);padding:10px;border-radius:10px;text-align:center;"> Vector norms</h2>

<h3>L1 Norm</h3>
<p>The L
1 norm is calculated as the sum of the absolute vector values, where the absolute value
of a scalar uses the notation |a1|. In effect, the norm is a calculation of the Manhattan distance
from the origin of the vector space.<br>
||v||1 = |a1| + |a2| + |a3| 
</p>

<h3>L2 Norm</h3>
<p>
    The L
2 norm calculates the distance of the vector coordinate from the origin of the vector
space. As such, it is also known as the Euclidean norm as it is calculated as the Euclidean
distance from the origin. The result is a positive distance value. The L
2 norm is calculated as
the square root of the sum of the squared vector values.
||v||2 = sqrt((a1**2)+a2**2+a3**2)
</p>
<h3>Max/Inf Norm</h3>
<p>

The max norm is calculated as returning the maximum value of the vector, hence the name.
||v||inf = max a1, a2, a3 
</p>

In [9]:
#L2 Norm in NUMPY
l2=np.linalg.norm(v1)
#L1 Norm in NUMPY
l1=np.linalg.norm(v1,1)
#Max/inf Norm in NUMPY
maxn=np.linalg.norm(v1,inf)
print(str(l1)+"|  "+str(l2)+"|  "+str(maxn))

#Implementing each operation manually
#let v be a vector
v=[[1,2,3]]
#L1 norm
print(sum(v[0]))
#max norm
print(max(v[0]))
#l2 norm


def dot(v,w):
    return sum(vi*wi for vi,wi in zip(v,w))

dot(v1,v2)


6.0|  3.7416573867739413|  3.0
6
3


14